name: forex-prices

on:
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 4 * * *'
    - cron: '0 5 * * *'
    - cron: '0 6 * * *'
    - cron: '0 7 * * *'
    - cron: '0 8 * * *'
    - cron: '0 9 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  post-forex-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python forex_price_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
